<a href="https://colab.research.google.com/github/Varshithanelli/Tensor_datatypes_and_aggregate_functions/blob/main/Tensor_datatypes%26aggregate_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#create a tensor of all zeroes
zeroes=torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
 #creating a range of tensors and tensors-like
one_to_ten=torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
tenzeroes=torch.zeros_like(input=one_to_ten)
tenzeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes


In [ ]:
# float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
# creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5064, 0.6215, 0.5746, 0.6891],
        [0.6937, 0.6348, 0.7355, 0.5343],
        [0.2940, 0.3393, 0.4858, 0.8441]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.5064, 0.6215, 0.5746, 0.6891],
        [0.6937, 0.6348, 0.7355, 0.5343],
        [0.2940, 0.3393, 0.4858, 0.8441]])
datatype of tensor: torch.float32
shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


In [ ]:
#manipulating tensors(tensor operations)
tensor=torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
#element wise multiplication
print(tensor," *",tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3])  * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 137 µs, sys: 834 µs, total: 971 µs
Wall time: 2.49 ms


tensor(14)

In [ ]:
# one of the most common errors in deep learning
#shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10,8],
                       [9,12,4]])
torch.matmul(tensor_A,tensor_B)

tensor([[ 25,  34,  16],
        [ 57,  78,  40],
        [ 89, 122,  64]])

In [ ]:
#transpose of a matrix
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
#creating a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))